[features]
seeds = false
skip-lint = false
[programs.localnet]
calc = "8HUpvKLtMPXq1mZRkiKyKdgMGQ1S7yKnL1BKokNUoztT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/macp/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
